#!/bin/bash

#Update the entire system
yes | sudo apt-get update
yes | sudo apt-get dist-upgrade

#Install basic programs
yes | sudo apt-get install git vim python3 python3-pip neofetch make docker.io docker-compose

#Clone DotFiles
cd ~
git clone https://github.com/artic42/DotFiles.git

#Execute non-distro dependeding part
sh ~/DotFiles/script/copyConf
