#!/bin/bash

#Update the entire system
yes | sudo dnf upgrade

#Install basic programs
yes | sudo dnf install git gcc gdb vim python3 python3-pip neofetch ctags tmux make rxvt-unicode texlive-scheme-basic
yes | sudo pip3 install powerline-shell

#Clone DotFiles
cd ~
git clone https://github.com/artic42/DotFiles.git

#Execute non-distro dependeding part
sh ~/DotFiles/script/copyConf

#Last order is to reboot
~/.script/promptReboot.sh
