#!/bin/bash
read -p "What theme do yu want Light or Dark?" response
if [ "$response" == "l" ]; then
	cp ~/.vim/theme/vim-theme-light ~/.vim/theme/vim-theme
fi

if [ "$response" == "d" ]; then
	cp ~/.vim/theme/vim-theme-dark ~/.vim/theme/vim-theme
fi

